import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <nav className="my-1 nav-container fixed top-0 w-full z-10 bg-white">
          <NavBar />
        </nav>
        <section className='mt-28'>
          {children}
        </section>
        <Footer />
      </body>
    </html>
  )
}
